services:
  app:
    image: bdc2026
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/data:/app/data:ro
      - ./app/output:/app/output
      - ./app/temp:/app/temp
    command: ["/bin/bash", "/app/data/run.sh"]
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
